name: Go

on:
  push:
    branches: [ master, release-0.1 ]
  pull_request:
    branches: [ master, release-0.1 ]

defaults:
  run:
    shell: bash
    working-directory: gatekeeper-operator

jobs:
  main:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go: [ '1.15' ]
    name: Go ${{ matrix.go }}
    steps:
    - name: Checkout Gatekeeper Operator
      uses: actions/checkout@v2
      with:
        path: gatekeeper-operator
        fetch-depth: 0 # Fetch all history for all tags and branches

    - uses: actions/setup-go@v2
      id: go
      with:
        go-version: ${{ matrix.go }}

    - name: Verify modules
      run: go mod verify

    - name: Verify format
      run: |
        make fmt
        git diff --exit-code

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
        version: v1.37.1

    - name: Verify manifests
      run: |
        make manifests
        git diff --exit-code

    - name: Set Up Environment Variables
      run: |
        GATEKEEPER_VERSION=$(awk '/^GATEKEEPER_VERSION/ {print $3}' Makefile)
        echo "GATEKEEPER_VERSION=${GATEKEEPER_VERSION}" >> ${GITHUB_ENV}

    # This step is necessary to use a local clone of the Gatekeeper repo.
    # Otherwise kustomize bulid fails using the go-getter URL format as result
    # of https://github.com/open-policy-agent/gatekeeper/issues/1112. Also see
    # https://github.com/kubernetes-sigs/kustomize/issues/3515 for a feature
    # request.
    - name: Checkout Gatekeeper to verify imported manifests
      uses: actions/checkout@v2
      with:
        repository: open-policy-agent/gatekeeper
        ref: ${{ env.GATEKEEPER_VERSION }}
        path: gatekeeper
        fetch-depth: 0 # Fetch all history for all tags and branches

    # Build Gatekeeper manifests with some workarounds due to issue described
    # above.
    - name: Prepare Gatekeeper manifests for importing
      working-directory: gatekeeper
      run: |
        make patch-image IMG=openpolicyagent/gatekeeper:${GATEKEEPER_VERSION}
        sed -i '/--emit-\(audit\|admission\)-events/d' config/overlays/dev/manager_image_patch.yaml

    - name: Verify imported manifests
      run: |
        make import-manifests IMPORT_MANIFESTS_PATH=${GITHUB_WORKSPACE}/gatekeeper
        git diff --exit-code

    - name: Verify bindata
      run: |
        make verify-bindata

    - name: Verify bundle
      run: |
        make bundle
        git diff --exit-code

    - name: Create K8s KinD Cluster
      run: kind create cluster --image kindest/node:v1.19.7

    - name: Build and Push Test Container Image to KIND node
      run: |
        make docker-build IMG=localhost:5000/gatekeeper-operator:$GITHUB_SHA
        kind load docker-image localhost:5000/gatekeeper-operator:$GITHUB_SHA

    - name: Unit and Integration Tests
      run: make test

    - name: E2E Tests
      run: |
        make deploy-ci NAMESPACE=mygatekeeper IMG=localhost:5000/gatekeeper-operator:$GITHUB_SHA
        make test-e2e NAMESPACE=mygatekeeper
        kubectl delete --wait namespace mygatekeeper

    - name: Gatekeeper E2E Tests
      run: |
        sudo apt-get install -y bats
        make deploy-ci NAMESPACE=gatekeeper-system IMG=localhost:5000/gatekeeper-operator:$GITHUB_SHA
        make test-gatekeeper-e2e ENABLE_MUTATION_TESTS=y
